### ISSUE TITLE
pipeline.require.<source>.status should accept a list

### ISSUE THREAD

**Issue by martimmatias** [codesquadnest/zuullint#138]
### The problem
Similar to #135
[pipeline.require.&lt;github source&gt;.status](https://zuul-ci.org/docs/zuul/latest/drivers/github.html#attr-pipeline.require.%3Cgithub%20source%3E.status) should accept either a string or a list of strings, as evidenced by [this source-code section](https://opendev.org/zuul/zuul/src/commit/82df4a082226fcda6bc7207fd04b63caf22f073d/zuul/driver/github/githubsource.py#L225).

The same is true for gerrit, [evidence](https://opendev.org/zuul/zuul/src/commit/82df4a082226fcda6bc7207fd04b63caf22f073d/zuul/driver/gerrit/gerritsource.py#L273).

### Reproducing:
The following code raises an error:
```yaml
- pipeline:
    name: foo
    manager: independent
    require:
      github:
        status:
            - zuul:example:success
```
