### ISSUE TITLE
Warn when a semaphore is specified as both a job and playbook semaphore

### ISSUE THREAD

**Issue by martimmatias** [codesquadnest/zuullint#48]
Zuul does not allow a semaphore to be specified both in job.semaphores and job.&lt;run-type&gt;.semaphores properties.
Warn or give an error when a semaphore is specified by its name in both locations.

For example, the following job definition would raise an error:
```yaml
- job:
    name: test-run-semaphores
    semaphores:
      - test-run-semaphore
    run:
      - name: playbooks/test-run-semaphores.yaml
        semaphores: test-run-semaphore
```
The error:
`Semaphores {'test-run-semaphore'} specified as both job and playbook semaphores but may only be used for one`
